### ISSUE TITLE
Thank you sir

### ISSUE THREAD

**Issue by LISPos** [gabrielchristo/qml-tableview#1]
Hello
I have a question.
I want to know how to add columns to Tableview during program operation.
For example, I want to increase the column by clicking the button.
Your source is very helpful.
Could you possibly answer the question?
Thank you for reading my poor English sentences.

**Comment by gabrielchristo** [comment]
> Hello
> I have a question.
> I want to know how to add columns to Tableview during program operation.
> For example, I want to increase the column by clicking the button.
> Your source is very helpful.
> Could you possibly answer the question?
> Thank you for reading my poor English sentences.

Hello
I did not have in mind dynamic columns when i created the code
I can only recommend you two ways of doing so:
-  [Dynamic creation](https://stackoverflow.com/questions/27230818/qml-tableview-with-dynamic-number-of-columns/27247370) of TableViewColumn or TableModelColumn

- Create your own table model (C++) by extend [qt model classes](https://doc.qt.io/qt-5/qabstracttablemodel.html) and connect to qml
